substitutions:
  board: esp32-c3-devkitm-1
  tx_pin: GPIO20
  rx_pin: GPIO19
  baud_rate: "9600"

esphome:
  platformio_options:
    board_build.flash_mode: dio
    build_flags:
      - -std=gnu++17
    build_unflags:
      - -std=gnu++11

esp32:
  board: $board
  framework:
    type: esp-idf

wifi:
  power_save_mode: none

logger:
  # Make sure logging is not using the serial port
  baud_rate: 0

uart:
  - id: uart_tion
    tx_pin: $tx_pin
    rx_pin: $rx_pin
    baud_rate: $baud_rate
# esp32_usb_dis:
